### ISSUE TITLE
A better way to parse JSON strings?

### ISSUE THREAD

**Issue by michaellenaghan** [spc476/LPeg-Parsers#3]
I'm just a few days into learning LPeg. The code in this repository helped me get over some serious humps in the learning process. Thank you!

I may have come up with a better way to parse JSON strings. 

Here's the current approach:

https://github.com/spc476/LPeg-Parsers/blob/e9dd8bc6cc15a9dceba3233f09abf73a1e0bc302/json.lua#L93-L108

Here's a different approach:

```lua
local G = re.compile([[
    string <- '"' {~ <character>* ~} '"'
    character <- <escaped> / <unescaped>
    escaped <-
        '\' -> '' (
            '"' -> json_double_quote /
            '\' -> json_reverse_solidus /
            '/' -> json_solidus /
            'b' -> json_backspace /
            'f' -> json_formfeed /
            'n' -> json_linefeed /
            'r' -> json_carriage_return /
            't' -> json_horizontal_tab /
            'u' -> '' %x^4 -> json_unicode
        )
    unescaped <- %json_char
]], {
    json_double_quote = "\"",
    json_reverse_solidus = "\\",
    json_solidus = "/",
    json_backspace = "\b",
    json_formfeed = "\f",
    json_linefeed = "\n",
    json_carriage_return = "\r",
    json_horizontal_tab = "\t",
    json_unicode = string.char,
    json_char = lpeg.utfR(0x0020, 0x10ffff) - lpeg.S([["\]]),
})
```

So why "better"?

The `{~ … ~}` in the second line is a "substitution capture."

* Notice that LPeg does the work of accumulating the captured value; there's no table capture, and no call to something like `final_string()` (which then calls `table.concat()`).
* Notice that almost all of the substitutions are values rather than function calls.

I haven't tested, but I presume those two things mean that this approach is better on time and space.

P.S. I don't know if this is an LPeg 1.1 thing, but also possibly of interest:

```
json_char = lpeg.utfR(0x0020, 0x10ffff) - lpeg.S([["\]])
```

That validates UTF8. Not just that, but the current approach:

```
unescaped       <- [^\"%c]
```

fails on `0x7f`, which is considered a control character:

```lua
> if string.match("\x7f", "%c") then print("matched") end
matched
```

According to the spec `0x7f` is a valid JSON character.

**Comment by spc476** [comment]
Using "{~ ~}" might indeed be better and more direct.  I don't know about the proposed changes to `escaped` though---if the code switches to using the substitution capture, we might as well express `escaped` as in the jsons.lua module, in direct LPEG.  

As far as lpeg.utfR() though, that is LPEG 1.1 specific, and I'd be hesitant to insist upon using that when LPEG 1.0 is working. It is odd that 0x7F is accepted as valid JSON, but yes, I checked and indeed it is.

**Comment by michaellenaghan** [comment]
> if the code switches to using the substitution capture, we might as well express `escaped` as in the jsons.lua module, in direct LPEG

Ah, I hadn't looked at `jsons.lua`; yes, what I did is exactly what you did there, just in `re` notation. 

> …is accepted as valid JSON…

One other spec note, in case you're interested: JSON allows any kind of value at the top, not just arrays and objects.

I'll go ahead and close this. Thanks for making all of this available; I've been poking through `lua-conman` too.

P.S. If you haven't seen [`redbean`](https://redbean.dev) you should take a look. I was able to create a "Hello, world" thing on my Mac, copy the *same executable* to my FreeBSD-based shared host, and then use the *same executable* in a bare bones Docker on fly.io. Quite incredible.
